#SPDX-License-Identifier: MIT-0
---
# tasks file for registry
- name: Pull registry image
  ansible.builtin.command: docker pull "{{ registry_image }}"
  register: registry_image_pull
  changed_when: "'Downloaded newer image' in registry_image_pull.stdout or 'Pull complete' in registry_image_pull.stdout"

- name: Ensure registry data volumne exists
  ansible.builtin.command: docker volume create "{{ registry_data_volume }}"
  register: registry_volume
  changed_when: "registry_data_volume in registry_volume.stdout"

- name: Remove old registry container
  ansible.builtin.command: docker rm -f "{{ registry_container_name }}"
  register: registry_container_remove
  failed_when: false
  changed_when: registry_container_remove.rc == 0

- name: Run registry container
  ansible.builtin.command:
    argv:
      - docker
      - run
      - -d
      - --name
      - "{{ registry_container_name }}"
      - --restart
      - unless-stopped
      - -p
      - "{{ registry_http_port }}:5000"
      # Cho phép xoá image (UI joxit gọi DELETE /v2/.../manifests/<digest>)
      - -e
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
      - -v
      - "{{ registry_data_volume }}:/var/lib/registry"
      - "{{ registry_image }}"
